
[toolchain]
  channel = "1.94.1"
  components = ["clippy", "llvm-tools-preview", "rust-analyzer", "rustfmt"]
  profile = "minimal"
  targets = ["aarch64-unknown-linux-musl", "wasm32-wasip1", "x86_64-unknown-linux-musl"]
