/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/go-logr/logr"

	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	apimeta "k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	policiesv1 "github.com/kubewarden/adm-controller/api/policies/v1"
	"github.com/kubewarden/adm-controller/internal/constants"
)

// Warning: this controller is deployed by a helm chart which has its own
// templated RBAC rules. The rules are kept in sync between what is generated by
// `make manifests` and the helm chart by hand.
//
// We need access to these resources only inside of the namespace where the
// controller is deployed. Here we assume it's being deployed inside of the
// `kubewarden` namespace, this has to be parametrized in the helm chart
//+kubebuilder:rbac:groups=policies.kubewarden.io,resources=policyservers,verbs=get;list;watch;delete;create;update;patch
//+kubebuilder:rbac:groups=policies.kubewarden.io,resources=policyservers/status,verbs=get;update;patch
//+kubebuilder:rbac:groups=policies.kubewarden.io,resources=policyservers/finalizers,verbs=update
//+kubebuilder:rbac:namespace=kubewarden,groups=core,resources=secrets;services;configmaps,verbs=get;list;watch;create;update;patch;delete
//+kubebuilder:rbac:namespace=kubewarden,groups=apps,resources=deployments,verbs=create;update;patch;delete;get;list;watch
//+kubebuilder:rbac:namespace=kubewarden,groups=apps,resources=replicasets,verbs=get;list;watch
//+kubebuilder:rbac:namespace=kubewarden,groups=core,resources=pods,verbs=get;list;watch
//+kubebuilder:rbac:namespace=kubewarden,groups=policy,resources=poddisruptionbudgets,verbs=get;list;watch;create;update;patch;delete

// PolicyServerReconciler reconciles a PolicyServer object.
type PolicyServerReconciler struct {
	client.Client
	TelemetryConfiguration
	Log                                                logr.Logger
	Scheme                                             *runtime.Scheme
	DeploymentsNamespace                               string
	AlwaysAcceptAdmissionReviewsInDeploymentsNamespace bool
	ClientCAConfigMapName                              string
	// ImagePullSecrets is the list of image pull secrets to add to every
	// policy-server Deployment, sourced from the controller's own
	// --image-pull-secrets flag.
	ImagePullSecrets []corev1.LocalObjectReference
	// HostNetwork enables host network mode on PolicyServer Deployments.
	// When true, the controller also sets dnsPolicy to ClusterFirstWithHostNet
	// so that in-cluster DNS resolution keeps working.
	HostNetwork bool
	// PolicyServerMetricsPort is the global default metrics port for PolicyServer
	// Service objects. It is populated from the --policy-server-metrics-port CLI
	// flag at startup, falling back to the deprecated
	// KUBEWARDEN_POLICY_SERVER_SERVICES_METRICS_PORT env var and then to
	// constants.PolicyServerMetricsPort.
	// A per-PolicyServer CRD field (spec.metricsPort) always takes priority.
	PolicyServerMetricsPort int32
}

// TelemetryConfiguration is a struct that contains the configuration for the
// Telemetry configuration. Now, it only contains the configuration for the
// OpenTelemetry.
type TelemetryConfiguration struct {
	MetricsEnabled bool
	TracingEnabled bool
	// OpenTelemetry configuration.
	// OtelSidecarEnabled is a flag that enables the OpenTelemetry sidecar.
	OtelSidecarEnabled bool
	// OtelCertificateSecret and OtelClientCertificateSecret are the names of the
	// secrets that contain the certificates used with the communication between
	// controller and policy server with the remote OpenTelemetry collector.
	OtelCertificateSecret       string
	OtelClientCertificateSecret string
}

func (r *PolicyServerReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	var policyServer policiesv1.PolicyServer
	if err := r.Get(ctx, req.NamespacedName, &policyServer); err != nil {
		if client.IgnoreNotFound(err) != nil {
			return ctrl.Result{}, fmt.Errorf("failed to get policy server: %w", err)
		}
		return ctrl.Result{}, nil
	}

	if policyServer.ObjectMeta.DeletionTimestamp != nil {
		return r.reconcileDeletion(ctx, &policyServer)
	}

	err := r.reconcilePolicyServerCertSecret(ctx, &policyServer)
	if err != nil {
		return ctrl.Result{}, err
	}

	policies, err := r.getPolicies(ctx, &policyServer)
	if err != nil {
		return ctrl.Result{}, errors.Join(errors.New("could not get policies"), err)
	}

	if err = r.reconcilePolicyServerConfigMap(ctx, &policyServer, policies); err != nil {
		setFalseConditionType(
			&policyServer.Status.Conditions,
			string(policiesv1.PolicyServerConfigMapReconciled),
			fmt.Sprintf("error reconciling configmap: %v", err),
		)
		return ctrl.Result{}, err
	}

	setTrueConditionType(
		&policyServer.Status.Conditions,
		string(policiesv1.PolicyServerConfigMapReconciled),
	)

	if err = r.reconcilePolicyServerPodDisruptionBudget(ctx, &policyServer); err != nil {
		setFalseConditionType(
			&policyServer.Status.Conditions,
			string(policiesv1.PolicyServerPodDisruptionBudgetReconciled),
			fmt.Sprintf("error reconciling policy server PodDisruptionBudget: %v", err),
		)
		return ctrl.Result{}, err
	}

	setTrueConditionType(
		&policyServer.Status.Conditions,
		string(policiesv1.PolicyServerPodDisruptionBudgetReconciled),
	)

	if err = r.reconcilePolicyServerDeployment(ctx, &policyServer); err != nil {
		setFalseConditionType(
			&policyServer.Status.Conditions,
			string(policiesv1.PolicyServerDeploymentReconciled),
			fmt.Sprintf("error reconciling deployment: %v", err),
		)
		return ctrl.Result{}, err
	}

	setTrueConditionType(
		&policyServer.Status.Conditions,
		string(policiesv1.PolicyServerDeploymentReconciled),
	)

	if err = r.reconcilePolicyServerService(ctx, &policyServer); err != nil {
		setFalseConditionType(
			&policyServer.Status.Conditions,
			string(policiesv1.PolicyServerServiceReconciled),
			fmt.Sprintf("error reconciling service: %v", err),
		)
		return ctrl.Result{}, err
	}

	setTrueConditionType(
		&policyServer.Status.Conditions,
		string(policiesv1.PolicyServerServiceReconciled),
	)

	if err = r.Client.Status().Update(ctx, &policyServer); err != nil {
		return ctrl.Result{}, fmt.Errorf("update policy server status error: %w", err)
	}

	return ctrl.Result{}, nil
}

// SetupWithManager sets up the controller with the Manager.
func (r *PolicyServerReconciler) SetupWithManager(mgr ctrl.Manager) error {
	err := mgr.GetFieldIndexer().IndexField(context.Background(), &policiesv1.ClusterAdmissionPolicy{}, constants.PolicyServerIndexKey, func(object client.Object) []string {
		policy, ok := object.(*policiesv1.ClusterAdmissionPolicy)
		if !ok {
			r.Log.Error(nil, "object is not type of ClusterAdmissionPolicy: %#v", "policy", policy)
			return []string{}
		}
		return []string{policy.Spec.PolicyServer}
	})
	if err != nil {
		return fmt.Errorf("failed enrolling controller with manager: %w", err)
	}
	err = mgr.GetFieldIndexer().IndexField(context.Background(), &policiesv1.AdmissionPolicy{}, constants.PolicyServerIndexKey, func(object client.Object) []string {
		policy, ok := object.(*policiesv1.AdmissionPolicy)
		if !ok {
			r.Log.Error(nil, "object is not type of AdmissionPolicy: %#v", "policy", policy)
			return []string{}
		}
		return []string{policy.Spec.PolicyServer}
	})
	if err != nil {
		return fmt.Errorf("failed enrolling controller with manager: %w", err)
	}
	err = mgr.GetFieldIndexer().IndexField(context.Background(), &policiesv1.AdmissionPolicyGroup{}, constants.PolicyServerIndexKey, func(object client.Object) []string {
		policy, ok := object.(*policiesv1.AdmissionPolicyGroup)
		if !ok {
			r.Log.Error(nil, "object is not type of AdmissionPolicyGroup: %#v", "policy", policy)
			return []string{}
		}
		return []string{policy.Spec.PolicyServer}
	})
	if err != nil {
		return fmt.Errorf("failed enrolling controller with manager: %w", err)
	}
	err = mgr.GetFieldIndexer().IndexField(context.Background(), &policiesv1.ClusterAdmissionPolicyGroup{}, constants.PolicyServerIndexKey, func(object client.Object) []string {
		policy, ok := object.(*policiesv1.ClusterAdmissionPolicyGroup)
		if !ok {
			r.Log.Error(nil, "object is not type of ClusterAdmissionPolicyGroup: %#v", "policy", policy)
			return []string{}
		}
		return []string{policy.Spec.PolicyServer}
	})
	if err != nil {
		return fmt.Errorf("failed enrolling controller with manager: %w", err)
	}

	err = ctrl.NewControllerManagedBy(mgr).
		For(&policiesv1.PolicyServer{}).
		Watches(&policiesv1.AdmissionPolicy{}, handler.EnqueueRequestsFromMapFunc(r.enqueueAdmissionPolicy)).
		Watches(&policiesv1.AdmissionPolicyGroup{}, handler.EnqueueRequestsFromMapFunc(r.enqueueAdmissionPolicyGroup)).
		Watches(&policiesv1.ClusterAdmissionPolicy{}, handler.EnqueueRequestsFromMapFunc(r.enqueueClusterAdmissionPolicy)).
		Watches(&policiesv1.ClusterAdmissionPolicyGroup{}, handler.EnqueueRequestsFromMapFunc(r.enqueueClusterAdmissionPolicyGroup)).
		Complete(r)
	if err != nil {
		return errors.Join(errors.New("failed enrolling controller with manager"), err)
	}
	return nil
}

func (r *PolicyServerReconciler) enqueueAdmissionPolicy(_ context.Context, object client.Object) []reconcile.Request {
	// The watch will trigger twice per object change; once with the old
	// object, and once the new object. We need to be mindful when doing
	// Updates since they will invalidate the newer versions of the
	// object.
	policy, ok := object.(*policiesv1.AdmissionPolicy)
	if !ok {
		r.Log.Info("object is not type of AdmissionPolicy: %+v", "policy", policy)
		return []ctrl.Request{}
	}

	return []ctrl.Request{
		{
			NamespacedName: client.ObjectKey{
				Name: policy.Spec.PolicyServer,
			},
		},
	}
}

func (r *PolicyServerReconciler) enqueueAdmissionPolicyGroup(_ context.Context, object client.Object) []reconcile.Request {
	// The watch will trigger twice per object change; once with the old
	// object, and once the new object. We need to be mindful when doing
	// Updates since they will invalidate the newer versions of the
	// object.
	policy, ok := object.(*policiesv1.AdmissionPolicyGroup)
	if !ok {
		r.Log.Info("object is not type of AdmissionPolicyGroup: %+v", "policy", policy)
		return []ctrl.Request{}
	}

	return []ctrl.Request{
		{
			NamespacedName: client.ObjectKey{
				Name: policy.Spec.PolicyServer,
			},
		},
	}
}

func (r *PolicyServerReconciler) enqueueClusterAdmissionPolicy(_ context.Context, object client.Object) []reconcile.Request {
	// The watch will trigger twice per object change; once with the old
	// object, and once the new object. We need to be mindful when doing
	// Updates since they will invalidate the newer versions of the
	// object.
	policy, ok := object.(*policiesv1.ClusterAdmissionPolicy)
	if !ok {
		r.Log.Info("object is not type of ClusterAdmissionPolicy: %+v", "policy", policy)
		return []ctrl.Request{}
	}

	return []ctrl.Request{
		{
			NamespacedName: client.ObjectKey{
				Name: policy.Spec.PolicyServer,
			},
		},
	}
}

func (r *PolicyServerReconciler) enqueueClusterAdmissionPolicyGroup(_ context.Context, object client.Object) []reconcile.Request {
	// The watch will trigger twice per object change; once with the old
	// object, and once the new object. We need to be mindful when doing
	// Updates since they will invalidate the newer versions of the
	// object.
	policy, ok := object.(*policiesv1.ClusterAdmissionPolicyGroup)
	if !ok {
		r.Log.Info("object is not type of ClusterAdmissionPolicyGroup: %+v", "policy", policy)
		return []ctrl.Request{}
	}

	return []ctrl.Request{
		{
			NamespacedName: client.ObjectKey{
				Name: policy.Spec.PolicyServer,
			},
		},
	}
}

// getPolicies returns all admission policies, cluster admission policies,
// admission policy groups and cluster admission policy groups bound to the
// given policyServer.
func (r *PolicyServerReconciler) getPolicies(ctx context.Context, policyServer *policiesv1.PolicyServer) ([]policiesv1.Policy, error) {
	var clusterAdmissionPolicies policiesv1.ClusterAdmissionPolicyList
	if err := r.Client.List(ctx, &clusterAdmissionPolicies, client.MatchingFields{constants.PolicyServerIndexKey: policyServer.Name}); err != nil {
		return nil, fmt.Errorf("failed obtaining ClusterAdmissionPolicies: %w", err)
	}
	var admissionPolicies policiesv1.AdmissionPolicyList
	if err := r.Client.List(ctx, &admissionPolicies, client.MatchingFields{constants.PolicyServerIndexKey: policyServer.Name}); err != nil {
		return nil, fmt.Errorf("failed obtaining AdmissionPolicies: %w", err)
	}

	var admissionPolicyGroupList policiesv1.AdmissionPolicyGroupList
	if err := r.Client.List(ctx, &admissionPolicyGroupList, client.MatchingFields{constants.PolicyServerIndexKey: policyServer.Name}); err != nil {
		return nil, fmt.Errorf("failed obtaining AdmissionPolicyGroups: %w", err)
	}

	var clusterAdmissionPolicyGroupList policiesv1.ClusterAdmissionPolicyGroupList
	if err := r.Client.List(ctx, &clusterAdmissionPolicyGroupList, client.MatchingFields{constants.PolicyServerIndexKey: policyServer.Name}); err != nil {
		return nil, fmt.Errorf("failed obtaining ClusterAdmissionPolicyGroups: %w", err)
	}

	policies := make([]policiesv1.Policy, 0)
	for _, clusterAdmissionPolicy := range clusterAdmissionPolicies.Items {
		policies = append(policies, clusterAdmissionPolicy.DeepCopy())
	}
	for _, admissionPolicy := range admissionPolicies.Items {
		policies = append(policies, admissionPolicy.DeepCopy())
	}
	for _, admissionPolicyGroup := range admissionPolicyGroupList.Items {
		policies = append(policies, admissionPolicyGroup.DeepCopy())
	}
	for _, clusterAdmissionPolicyGroup := range clusterAdmissionPolicyGroupList.Items {
		policies = append(policies, clusterAdmissionPolicyGroup.DeepCopy())
	}
	return policies, nil
}

// reconcileDeletion waits for the webhook configurations of all bound policies
// to be removed before releasing the PolicyServer finalizers. The
// PolicyWebhooksCleanedUp condition tracks progress:
//   - False: webhooks still exist; requeue with a short delay.
//   - True: all webhooks gone; remove finalizers on the next reconcile loop so
//     the fresh resourceVersion from the status update is used.
func (r *PolicyServerReconciler) reconcileDeletion(ctx context.Context, policyServer *policiesv1.PolicyServer) (ctrl.Result, error) {
	// If the condition is already True the previous reconcile already confirmed
	// all webhooks are gone. Remove the finalizers using the freshly-fetched
	// object (guaranteed by Reconcile calling r.Get before reaching here).
	if apimeta.IsStatusConditionTrue(policyServer.Status.Conditions, string(policiesv1.PolicyServerPolicyWebhooksCleanedUp)) {
		return r.removeFinalizers(ctx, policyServer)
	}

	policies, err := r.getPolicies(ctx, policyServer)
	if err != nil {
		return ctrl.Result{}, err
	}

	// Check policies assigned to this PolicyServer and wait until their
	// WebhookConfiguration is gone. Retry by returning and requeuing; cheaper
	// than adding a watch on WebhookConfigurations on PolicyServers.
	remaining := []string{}
	for _, policy := range policies {
		name := policy.GetUniqueName()
		var validatingFound bool
		validatingFound, err = r.webhookExists(ctx, name, &admissionregistrationv1.ValidatingWebhookConfiguration{})
		if err != nil {
			return ctrl.Result{}, fmt.Errorf("cannot check ValidatingWebhookConfiguration %q: %w", name, err)
		}
		if validatingFound {
			remaining = append(remaining, name)
			continue
		}
		var mutatingFound bool
		mutatingFound, err = r.webhookExists(ctx, name, &admissionregistrationv1.MutatingWebhookConfiguration{})
		if err != nil {
			return ctrl.Result{}, fmt.Errorf("cannot check MutatingWebhookConfiguration %q: %w", name, err)
		}
		if mutatingFound {
			remaining = append(remaining, name)
		}
	}
	if len(remaining) > 0 {
		setFalseConditionType(
			&policyServer.Status.Conditions,
			string(policiesv1.PolicyServerPolicyWebhooksCleanedUp),
			fmt.Sprintf("Waiting for webhook cleanup of policies: %s", strings.Join(remaining, ", ")),
		)
		if err = r.Client.Status().Update(ctx, policyServer); err != nil {
			return ctrl.Result{}, fmt.Errorf("cannot update policy server status: %w", err)
		}
		return ctrl.Result{RequeueAfter: constants.TimeToRequeuePolicyReconciliation}, nil
	}

	setTrueConditionType(
		&policyServer.Status.Conditions,
		string(policiesv1.PolicyServerPolicyWebhooksCleanedUp),
	)
	if err = r.Client.Status().Update(ctx, policyServer); err != nil {
		return ctrl.Result{}, fmt.Errorf("cannot update policy server status: %w", err)
	}
	// Requeue so the next reconcile fetches the object with the updated
	// resourceVersion before calling r.Update to remove the finalizers.
	return ctrl.Result{Requeue: true}, nil
}

func (r *PolicyServerReconciler) removeFinalizers(ctx context.Context, policyServer *policiesv1.PolicyServer) (ctrl.Result, error) {
	// Remove the old finalizer used to ensure that the policy server created
	// before this controller version is deleted as well. As the upgrade path
	// supported by the Kubewarden project does not allow jumping versions, we
	// can safely remove this line of code after a few releases.
	controllerutil.RemoveFinalizer(policyServer, constants.KubewardenFinalizerPre114)
	controllerutil.RemoveFinalizer(policyServer, constants.KubewardenFinalizer)
	if err := r.Update(ctx, policyServer); err != nil {
		// return if PolicyServer was previously deleted
		if apierrors.IsConflict(err) {
			return ctrl.Result{}, nil
		}
		return ctrl.Result{}, fmt.Errorf("cannot update policy server: %w", err)
	}

	return ctrl.Result{}, nil
}

// webhookExists returns true if a webhook configuration with the given name
// exists, false if it does not exist, and an error for any transient API error.
func (r *PolicyServerReconciler) webhookExists(ctx context.Context, name string, obj client.Object) (bool, error) {
	err := r.Client.Get(ctx, types.NamespacedName{Name: name}, obj)
	if err == nil {
		return true, nil
	}
	if apierrors.IsNotFound(err) {
		return false, nil
	}
	return false, fmt.Errorf("cannot get %T %q: %w", obj, name, err)
}

func setFalseConditionType(
	conditions *[]metav1.Condition,
	conditionType string,
	message string,
) {
	apimeta.SetStatusCondition(
		conditions,
		metav1.Condition{
			Type:    conditionType,
			Status:  metav1.ConditionFalse,
			Reason:  string(policiesv1.ReconciliationFailed),
			Message: message,
		},
	)
}

func setTrueConditionType(conditions *[]metav1.Condition, conditionType string) {
	apimeta.SetStatusCondition(
		conditions,
		metav1.Condition{
			Type:   conditionType,
			Status: metav1.ConditionTrue,
			Reason: string(policiesv1.ReconciliationSucceeded),
		},
	)
}

func policyServerDeploymentName(policyServerName string) string {
	return "policy-server-" + policyServerName
}
