// Package report implements PolicyReports and ClusterPolicyReports.
// It does that by importing
// https://github.com/kubernetes-sigs/wg-policy-prototypes and its go module. At
// the time of writing, autogenerated client code and interfaces for
// PolicyReports only exist up until
// "sigs.k8s.io/wg-policy-prototypes/policy-report/pkg/api/wgpolicyk8s.io/v1alpha2",
// "v1beta1" is work in progress.
// See https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/master/policy-report/README.md
// for more info.
package report
