#!/bin/bash
policies="kubewarden-policies.tar.gz"
list="kubewarden-policies.txt"

usage () {
    echo "USAGE: $0 [--policies-list kubewarden-policies.txt] [--policies kubewarden-policies.tar.gz]"
    echo "  [-l|--policies-list path] text file with list of policies; one police per line."
    echo "  [-p|--policies path] tar.gz generated by kwctl save."
    echo "  [-h|--help] Usage message"
}

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -p|--policies)
        policies="$2"
        shift # past argument
        shift # past value
        ;;
        -l|--policies-list)
        list="$2"
        shift # past argument
        shift # past value
        ;;
        -h|--help)
        help="true"
        shift
        ;;
        *)
        usage
        exit 1
        ;;
    esac
done

if [[ $help ]]; then
    usage
    exit 0
fi

pulled=""
while IFS= read -r i; do
    [ -z "${i}" ] && continue
    if kwctl pull "${i}" > /dev/null 2>&1; then
        echo "Policy pull success: ${i}"
        pulled="${pulled} ${i}"
    else
        echo "Policy pull failed: ${i}"
    fi
done < "${list}"

echo "Creating ${policies} with $(echo ${pulled} | wc -w | tr -d '[:space:]') policies"
kwctl  save $(echo ${pulled}) --output ${policies}
