on:
  workflow_dispatch:
    inputs:
      version:
        description: "stack version (E.g: v1.32.0-rc2)"
        required: true
        type: string

name: Open release PR

permissions: {}

jobs:
  open-release-pr:
    name: "Open PR to release Admission Controller"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }} # zizmor: ignore[secrets-outside-env]
          private-key: ${{ secrets.APP_PRIVATE_KEY }} # zizmor: ignore[secrets-outside-env]

      - name: Install cargo-set-version
        run: cargo install --version 0.13.9 cargo-edit

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@2cc8e6d8e356d76b0280cdd03766c36596a0614e # v3.0.0
        with:
          # Pinned to v0.109.0 due to a behavior change in newer versions that breaks the update script
          version: v0.109.0

      - name: Install helm
        # Helm and helm plugins installation required by the updatecli release action
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0

      - name: Install helm values schema json plugin
        # Disable plugin verification until helm v4 is supported
        run: helm plugin install https://github.com/losisin/helm-values-schema-json.git --verify=false

      - name: Open PR with updatecli
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          UPDATECLI_GITHUB_OWNER: ${{ github.repository_owner }}
          RELEASE_VERSION: ${{ inputs.version }}
        run: |-
          updatecli compose apply --file ./updatecli/open-release-pr.yaml
