name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * 1" # 3:30 on Monday

jobs:
  update-dependencies:
    name: Update Go version, Helm charts dependencies and Hauler manifest
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@af341a800cdbcde3ddcebb7a62410ac06a78a207 # v3.1.2
        with:
          # The version is pinned for now to workaround an issue found during
          # the compose file exectution when updatecli reports "something wrong
          # happen" for the conditions
          version: v0.109.0

      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }} # zizmor: ignore[secrets-outside-env]
          private-key: ${{ secrets.APP_PRIVATE_KEY }} # zizmor: ignore[secrets-outside-env]

      - name: Update all dependencies
        env:
          UPDATECLI_GITHUB_OWNER: ${{ github.repository_owner }}
          UPDATECLI_GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          UPDATECLI_GITHUB_APP_INSTALLATION_ID: "${{ secrets.APP_INSTALLATION_ID }}" # zizmor: ignore[secrets-outside-env]
        run: |-
          updatecli compose apply --file ./updatecli/update-deps.yaml
